title = "Bénévolat"
languageCode = "fr"
defaultContentLanguage = "fr"
disableKinds = ["taxonomy","taxonomyTerm","sitemap","RSS"]

publishDir= "docs"
baseURL = "https://nfriedli.github.io/benevolat/"

canonifyURLs = true