title = "Bénévolat"
languageCode = "fr"
defaultContentLanguage = "fr"
disableKinds = ["taxonomy","taxonomyTerm","sitemap","RSS"]

publishDir= "public"
baseURL = "https://eren.ch/benevolat/"

# Les URLs canoniques sont utiles pour les tests sur https://nfriedli.github.io/benevolat
canonifyURLs = true
# canonifyURLs = false

cleanDestinationDir = true
disableFastRender = true

[minify]
minifyOutput = true
[minify.tdewolff.html]
keepDocumentTags = true
keepEndTags = true
keepQuotes = true

[params]
footer = """
Un outil d'auto-profilage proposé par l'EREN (Église réformée évangélique du canton de Neuchâtel). Des propositions vous sont faites à titre indicatif. 

N'hésitez jamais à contacter notre responsable du secteur bénévolat pour vous aider dans votre choix ou annoncer votre intérêt:

Martine Robert   
032 510 05 47  
martine.robert@eren.ch
"""